config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'about', to: 'about#index'
  get 'privacy', to: 'privacy#index'
  get 'terms', to: 'terms#index'
  get 'logins/login'
  get 'logins/sign_up'
  # get 'home/index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    get 'sign_up', to: 'users/registrations#new'
    get 'users/sign_out', to: 'users/sessions#destroy'
  end

  root 'home#index'

  resources :users, param: :nandeda_id do
    # @like 「いいね」した時に「votes」テーブルにレコードを作成
    # @unlike 自分の投票を削除
    # @voted 自分の投票の記事一覧を表示
    # member { patch "like", "unlike" }
    # collection { get "voted" }
    # collection { get "search" }
    # resources :messages, only: [:index,:show]
    resources :messages, param: :url_token do
      resources :likes, only: [:create, :destroy]
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  has_many :likes
  has_many :liked_users, through: :likes, source: :user

  validates :message_text, presence: true, length: { minimum: 1 }
  validates :answer_text, length: { maximum: 238 }
  validates :url_token, presence: true, uniqueness: true

  # 公開記事のみ
  scope :common, -> { where(status: 0) }
  # 下書き以外（公開・会員限定）
  scope :published, -> { where('status <> ?', 'draft') }
  # 下書き以外と、自分が書いた記事全部
  scope :full, ->(user) {
    where('user_id = ? OR status <> ?', user.id, 'draft')
  }
  # ログインしていればfull、していなければcommon
  scope :readable_for, ->(user) { user ? full(user) : common }

  def to_param
    url_token
  end
end

app/controllers/messages_controller.rb
# frozen_string_literal: true

class MessagesController < ApplicationController
  before_action :set_twitter_client
  # before_action :new_message, only: [:show, :new]
  $description = "なんでだッ!?は、匿名の人からツッコミの一言をもらって、あなたがボケを考えて答えることのできるサービスです。ボケとツッコミのワンセットを完成させてみんなで楽しんで下さい。"

  # 記事一覧
  def index
    if params[:user_id]
      # user_idのハッシュがあった時
      @user = User.find(params[:user_id])
      @user = User.find_by(nandeda_id: params[:user_nandeda_id])
      @messages = @user.messages.where(status: false).order(created_at: :desc).paginate(page: params[:page], per_page: 10)
    else
      @user = User.find_by(nandeda_id: params[:user_nandeda_id])
      # @messages = Message.all
      @message = Message.new
      @messages = @user.messages.where(status: false).order(created_at: :desc).paginate(page: params[:page], per_page: 10)
    end
    # @messages = @messages.readable_for(current_user)
    # .order(posted_at: :desc).paginate(page: params[:page], per_page: 20)
  end

  # 記事の詳細
  def show
    # @message = Message.find(params[:id])
    # @user = User.where(:id => params[:user_id]).first
    @user = User.find_by(nandeda_id: params[:user_nandeda_id])
    # @message = Message.readable_for(@user).find(params[:id])
    @message = Message.find_by(url_token: params[:url_token])
    @like = Like.new
  end

  # 新規登録フォーム
  def new
    @user = User.find_by(nandeda_id: params[:user_nandeda_id])
    @message = Message.new
  end

  # 編集
  def edit
    @user = User.find_by(nandeda_id: params[:user_nandeda_id])
    @message = current_user.messages.find_by(url_token: params[:url_token])
  end

  def create
    @message = Message.new(message_params)
    # @message.author = User.where(:id => params[:user_id]).first
    @message.author = User.find_by(nandeda_id: params[:user_nandeda_id])

    # ipを保存
    @message.customer_ip = request.remote_ip

    # ハッシュを保存
    @message.url_token = SecureRandom.hex(10)

    if Message.last.present?
      next_id = Message.last.id + 1
    else
      next_id = 1
    end
    make_picture(next_id)

    if @message.save
      if @user.notification_allowed
        MessagesHelper.send(@user.email, @message.author.name, @message.url_token, url_for(only_path: false))
      end
      redirect_to controller: :messages, action: :index, notice: '作成しました。'
    else
      render 'new'
    end
  end

  def update
    @message = current_user.messages.find_by(url_token: params[:url_token])
    @message.assign_attributes(message_params)

    if @message.save
      # flagが立った時、ツイートする
      @twitter.update("#{@message.answer_text}\r\r#なんでだッ #Nandeda\r#{request.original_url}") if @message.twitter_flag && @message.status.blank?
      redirect_to controller: :messages, action: :index, notice: '更新しました。'
    else
      render 'edit'
    end
  end

  def destroy
    @message = current_user.messages.find_by(url_token: params[:url_token])
    @message.destroy
    redirect_to :messages, notice: '記事を削除しました。'
  end

  private

  def message_params
    params.require(:message).permit(:nandeda_id, :url_token, :customer_ip, :message_text, :message_image, :answer_text, :music_url, :status, :twitter_flag)
  end

  def set_twitter_client
    # @user = User.where(:id => params[:user_id]).first
    @user = User.find_by(nandeda_id: params[:user_nandeda_id])
    if @user.provider === 'twitter'
      @twitter = Twitter::REST::Client.new do |config|
        config.consumer_key        = @user.consumer_key
        config.consumer_secret     = @user.consumer_secret
        config.access_token        = @user.access_token
        config.access_token_secret = @user.access_token_secret
      end
    end
  end

  # ⑨メソッド追加（画像生成）
  def make_picture(id)
    sentense = ""
    # ⑨-1 改行を消去
    content = @message.message_text.gsub(/\r\n|\r|\n/," ")

    # ⑨-2 contentの文字数に応じて条件分岐
    if content.length <= 28 then
      # ⑨-3 28文字以下の場合は7文字毎に改行
      n = (content.length / 7).floor + 1
      n.times do |i|
        s_num = i * 7
        f_num = s_num + 6
        range =  Range.new(s_num,f_num)
        sentense += content.slice(range)
        sentense += "\n" if n != i+1
      end
      # ⑨-4 文字サイズの指定
      pointsize = 90
    elsif content.length <= 50 then
      n = (content.length / 10).floor + 1
      n.times do |i|
        s_num = i * 10
        f_num = s_num + 9
        range =  Range.new(s_num,f_num)
        sentense += content.slice(range)
        sentense += "\n" if n != i+1
      end
      pointsize = 60
    else
      n = (content.length / 15).floor + 1
      n.times do |i|
        s_num = i * 15
        f_num = s_num + 14
        range =  Range.new(s_num,f_num)
        sentense += content.slice(range)
        sentense += "\n" if n != i+1
      end
      pointsize = 45
    end

    # ⑨-5 文字色の指定
    color = "black"
    # ⑨-6 文字を入れる場所の調整（0,0を変えると文字の位置が変わります）
    draw = "text 0,0 '#{sentense}'"
    # ⑨-7 フォントの指定
    font = "./app/assets/fonts/geneinugothic-eb.ttf"
    # ⑨-8 ↑これらの項目も文字サイズのように背景画像や文字数によって変えることができます
    # ⑨-9 選択された背景画像の設定
    # case @post.kind
    # when "black" then
    #   base = "./app/assets/images/bg_image.png"
    #   # ⑨-10 今回は選択されていない場合は"red"となるようにしている
    # else
    #   base = "app/assets/images/red.jpg"
    # end
    base = "./app/assets/images/bg_image.png"
    # ⑨-11 minimagickを使って選択した画像を開き、作成した文字を指定した条件通りに挿入している
    image = MiniMagick::Image.open(base)
    image.combine_options do |i|
      i.font font
      i.fill color
      i.gravity 'center'
      i.pointsize pointsize
      i.draw draw
    end
    # ⑨-12 保存先のストレージの指定。Amazon S3を指定する。
    storage = Fog::Storage.new(
      provider: 'AWS',
      aws_access_key_id: ENV['AWS_ACCESS_KEY_ID'],
      aws_secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'],
      region: ENV['AWS_REGION']
    )
    # ⑨-13 開発環境or本番環境でS3のバケット（フォルダのようなもの）を分ける
    case Rails.env
    when 'production'
      # ⑨-14 バケットの指定・URLの設定
      bucket = storage.directories.get(ENV['AWS_S3_BUCKET'])
      # ⑨-15 保存するディレクトリ、ファイル名の指定（ファイル名は投稿id.pngとしています）
      image_name = SecureRandom.hex(10)
      png_path = 'uploads/entry/' + image_name + '.png'
      image_uri = image.path
      file = bucket.files.create(key: png_path, public: true, body: open(image_uri))
      @message.message_image = 'https://s3-ap-northeast-1.amazonaws.com/' + ENV['AWS_S3_BUCKET'] + "/" + png_path
    when 'development'
      bucket = storage.directories.get(ENV['AWS_S3_BUCKET'])
      image_name = SecureRandom.hex(10)
      png_path = 'uploads/entry/' + image_name + '.png'
      image_uri = image.path
      file = bucket.files.create(key: png_path, public: true, body: open(image_uri))
      @message.message_image = 'https://s3-ap-northeast-1.amazonaws.com/'+ ENV['AWS_S3_BUCKET'] + "/" + png_path
    end
  end
end

app/helpers/messages_helper.rb
# frozen_string_literal: true

module MessagesHelper
  require 'sendgrid-ruby'
  include SendGrid

  class << self

    def send(address, username, hash, url)
      from = SendGrid::Email.new(email: ENV['FROM_ADDRESS'])
      to = SendGrid::Email.new(email: address)
      subject = username + 'さん、あなたに質問が届きました！'
      hoge = address

      # ヒアドキュメント内で変数を使う場合、
      # #{x}で囲む
      str = <<-EOS
      あなたに質問が届きました！

      質問を確認する：#{url}/#{hash}
      EOS

      content = SendGrid::Content.new(type: 'text/plain', value: str)
      mail = SendGrid::Mail.new(from, subject, to, content)

      sg = SendGrid::API.new(api_key: ENV['SENDGRID_API_KEY'])
      response = sg.client.mail._('send').post(request_body: mail.to_json)
    end

  end
end

app/views/messages/_form.html.erb
<%#= render "shared/errors", obj: @entry %>

<div class="c-input">

  <% if current_user && @message.message_text %>
  <h3 class="c-batch--disabled">
    <span>届いたリクエスト</span>
  </h3>
  <div class="c-input__box">
    <%= image_tag @message.message_image, alt: @message.message_text %>
  </div>
  <% else %>
  <h3 class="c-batch--secondary">
    <span>リクエストを送る</span>
  </h3>
  <div class="c-input__box"><%= form.text_area :message_text %></div>
  <p id="c-validation__text"><span id="c-validation__count-entry">0</span>/140</p>
  <% end %>
</div>

<% if current_user && @message.message_text %>

<div class="c-input">
  <h3 class="c-batch--secondary">
    <span>アンサー</span>
  </h3>
  <div class="c-input__box"><%= form.text_area :answer_text, id: "c-validation__area", class: "form-control" %></div>
  <p id="c-validation__text"><span id="c-validation__count">0</span>/238</p>
</div>

<% if current_user.provider === "twitter" %>
<div class="c-switch">
  <%= form.label :twitter_flag, class: "c-switch__lable" do %>
  <%= form.check_box :twitter_flag, :as => :boolean, class: "c-switch__input" %>
  <span class="c-switch__content"></span>
  <span class="c-switch__circle"></span>
  <% end %>
  <p class="c-switch__text">twitterへ投稿します</p>
</div>
<% end %>

<div class="c-switch">
  <%= form.label :status, class: "c-switch__lable" do %>
  <%= form.check_box :status, :as => :boolean, class: "c-switch__input" %>
  <span class="c-switch__content"></span>
  <span class="c-switch__circle"></span>
  <% end %>
  <p class="c-switch__text">削除する</p>
</div>

<% end %>

app/views/messages/edit.html.erb
<% set_meta_tags title: @user.name + 'の質問一覧', description: @user.name + $description %>

<%= form_for [@user, @message], url: user_message_path do |form| %>
<%= render "form", form: form %>
<div class="c-btn--accent u-mt25">
  <%= form.submit id: "c-validation__submit" %>
</div>
<% end %>

app/views/messages/index.html.erb
<% set_meta_tags title: @user.name + 'の質問一覧', description: @user.name + $description %>

<%= form_for [@user, @message], url: user_messages_path do |form| %>
<%= render "form", form: form %>
<div class="c-btn--accent">
	<%= form.submit id: "c-validation__entry" %>
</div>
<% end %>

<div class="p-message">
	<h3 class="c-batch--secondary">
		<span>届いたリクエスト</span>
	</h3>

	<% if @messages.present? %>
	<ul class="c-message">
		<% @messages.each do |message| %>
		<li class="c-message__item">
			<%= link_to user_message_path(@user.nandeda_id, message), class: "c-message__item__link" do %>
			<% if message.answer_text %>
			<p class="c-answer__item__text">回答済み</p>
			<% end %>
			<p class="c-message__item__title"><%= message.message_text %></p>
			<p class="c-message__item__btn"><i class="fas fa-caret-right"></i> もっとみる</p>
			 いいね数：<%= message.liked_users.count %>
			<% end %>
		</li>
		<% end %>
		<% else %>
		<li class="c-message__item">
			<%= link_to user_messages_path(@user.nandeda_id), class: "c-message__item__link", data: {"turbolinks"=>false} do %>
			<p><%=@user.name%>さんにリクエストを送ろう！</p>
			<% end %>
		</li>
	</ul>
	<% end %>
	<%= will_paginate @messages, :class => 'p-pager' %>

</div>

app/views/messages/new.html.erb
<% set_meta_tags title: @user.name + 'の質問一覧', description: @user.name + $description %>

<%= form_for [@user, @message], url: user_messages_path do |form| %>
<%= render "form", form: form %>
<p><%= form.submit id: "c-validation__entry" %></p>
<% end %>

app/views/messages/show.html.erb
<% set_meta_tags title: @user.name + 'に届いた質問', description: @message.message_text + $description, og: { title: @message.message_text, image: @message.message_image } %>

<h3 class="c-batch--secondary">
	<span>届いたリクエスト</span>
</h3>

<% if @message.answer_text %>
<div class="c-answer__item">
	<h2 class="c-answer__item__text"><%= @user.name %>さんの回答</h2>
	<p class="c-answer__item__title"><%= raw Rinku.auto_link(@message.answer_text, :all, 'target="_blank"') %></p>
</div>
<% end %>

<div class="c-message">
	<div class="c-message__item">
		<div class="c-message__item__link">
			<%= image_tag @message.message_image, alt: @message.message_text %>
		</div>
	</div>
</div>

<% if current_user.already_liked?(@message) %>
  <%= button_to 'いいねを取り消す', user_message_like_path(@user.nandeda_id,  @message.id, @message.likes), method: :delete %>
<% else %>
  <%= button_to 'いいね', user_message_likes_path(@user.nandeda_id,  @message.id) %>
<% end %>
<h2>いいねしたユーザー</h2>
<% @message.liked_users.each do |user| %>
  <li><%= user.nandeda_id %></li>
<% end %>

<% if current_user == @message.author %>
	<div class="c-btn--accent u-mt25">
		<%= link_to "回答する", edit_user_message_path(@user.nandeda_id, @message), data: {"turbolinks"=>false} %>
	</div>
<% end %>