config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'about', to: 'about#index'
  get 'privacy', to: 'privacy#index'
  get 'terms', to: 'terms#index'
  get 'logins/login'
  get 'logins/sign_up'
  # get 'home/index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    get 'sign_up', to: 'users/registrations#new'
    get 'users/sign_out', to: 'users/sessions#destroy'
  end

  root 'home#index'

  resources :users, param: :nandeda_id do
    # @like 「いいね」した時に「votes」テーブルにレコードを作成
    # @unlike 自分の投票を削除
    # @voted 自分の投票の記事一覧を表示
    # member { patch "like", "unlike" }
    # collection { get "voted" }
    # collection { get "search" }
    # resources :messages, only: [:index,:show]
    resources :messages, param: :url_token do
      resources :likes, only: [:create, :destroy]
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_errors.html.erb
<% if obj.errors.present? %>
<div id="errors">
<h3>エラーがあります。</h3>
<ul>
  <% obj.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
  <% end %>
</ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<ul class="p-footer--small">
	<li>
		<%= link_to about_path, class:'' do %>
		<i class="fas fa-caret-right"></i> 使い方
		<% end %>
	</li>
	<li>
		<%= link_to terms_path, class:'' do %>
		<i class="fas fa-caret-right"></i> 利用規約
		<% end %>
	</li>
	<li>
		<%= link_to privacy_path, class:'' do %>
		<i class="fas fa-caret-right"></i> プライバシーポリシー
		<% end %>
	</li>
	<li>
		<a href="https://twitter.com/Nandeda_com" target="_blank">
		<i class="fas fa-caret-right"></i> 公式Twitter <i class="fas fa-external-link-alt"></i>
		</a>
	</li>
</ul>

app/views/shared/_header.html.erb
<header class="p-header">
	<div class="p-header__inner">
		<div class="p-header__logo">
			<%= link_to "なんでだッ!?-Nandeda-", root_path %>
		</div>
	</div>
</header>

app/views/shared/_login_form.html.erb
<h2>ログイン</h2>
<% if flash.alert %><p class="alert"><%= flash.alert %></p><% end %>
<%= form_tag :session do %>
<table id="login_form">
  <tr>
    <td style="text-align: right">ユーザー名：</td>
    <td><%= text_field_tag "name", "", style: "width:120px" %></td>
  </tr>
  <tr>
    <td style="text-align: right">パスワード：</td>
    <td><%= password_field_tag "password", "", style: "width:120px" %></td>
  </tr>
  <tr>
    <td colspan="2" style="text-align: center">
    <%= submit_tag "ログイン" %></td>
  </tr>
</table>
<% end %>

app/views/shared/_sidebar.html.erb
<h2>タグ一覧</h2>
<div id='tag_cloud'>
	<%# tag_cloud Entry.tag_counts, %w{s m l} do |tag, css_class| %>
	<%#= link_to tag.name, tag_path(tag.name), class: css_class %>
	<%# end %>
</div>

app/views/shared/_tab.html.erb
<%if user_signed_in? %>
<ul class="p-tab">
	<li class="p-tab__item">
		<%= link_to root_path, class:'' do %>
		<i class="fas fa-home"></i>
		<% end %>
	</li>
	<li class="p-tab__item">
		<%= link_to users_path, class:'' do %>
		<i class="far fa-user"></i>
		<% end %>
	</li>

	<li class="p-tab__item">
		<%= link_to user_messages_path(current_user.nandeda_id), class:'', data: {"turbolinks"=>false} do %>
		<i class="far fa-envelope"></i>
		<% end %>
	</li>

	<li class="p-tab__item">
		<%= link_to about_path, class:'', data: {"turbolinks"=>false} do %>
		<i class="far fa-question-circle"></i>
		<% end %>
	</li>

</ul>
<% end %>

<div class="p-footer">
	<p class="p-footer__copy">
		Copyright (C) 2018 <%= link_to "Nandeda", root_path %>
	</p>
</div>